### ISSUE TITLE
Trouble building and running on ArchLinux

### ISSUE THREAD

**Issue by steveunixson** [helloSystem/Filer#145]
Using a master branch, i've encoutered several problems

1. Filer/src/extattrs.cpp:30:25

```
error: ‘XATTR_NAMESPACE’ was not declared in this scope; did you mean ‘XATTR_NAME_MAX’?
   30 |   namespacedAttr.append(XATTR_NAMESPACE).append(".").append(attribute);
      |                         ^~~~~~~~~~~~~~~
      |                         XATTR_NAME_MAX
```
  
I've tried to change it as compiler suggests and then it builds fine but then I get a runtime error

`Failed qApp->installTranslator(qtTranslator)`

at src/filer.cpp 26:11

**Comment by probonopd** [comment]
While in principle Filer should compile on Linux, we are not testing this regularly. The best way to try out Filer currently is to run a helloSystem Live ISO.

Looks like these are two separate isssues
* Is `XATTR_NAMESPACE` not supported on Linux? What is its equivalent on Linux? I thought we had solved this in https://github.com/helloSystem/Filer/pull/37
* Why does `Failed qApp->installTranslator(qtTranslator)` happen and why does it result in a runtime error on Linux?

Seems like some people are using Filer on Linux:
https://www.reddit.com/r/kde/comments/wcmm6y/osx_style_global_menu_in_kde_plasma_a_kind_of/

![image](https://user-images.githubusercontent.com/2480569/196755473-cdc53414-8de9-472e-aa1a-f9f4ec31c219.png)

Possibly they have used this fork: https://github.com/mszoek/Filer
Does that one compile for you on Linux? If yes, then we have broken it since...

At this time, I am not investing (much) time into Linux support proactively, but at least having it build and run on Linux would be good, and I'd appreciate pull requests in this direction.

**Comment by probonopd** [comment]
Think we have fixed this since. Please retry and please comment here in case the issue persists. Thanks!
