### ISSUE TITLE
Do not open more than one window for the same location

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#17]
Instead, bring an existing window already showing that location to the front.

Especially useful if you have e.g., Ctl-Alt-A set to show `/Applications`.

**Comment by probonopd** [comment]
In or around `openFolder` and/or `DesktopWindow::onOpenDirRequested`, if a window or a tab exists with the path to be opened, do NOT open a new window but bring the existing window/tab to the front instead.

* How to find out whether we already have a window or tab open for a given path?
* Probably need to use `QWidget::raise()` and `QApplication::setActiveWindow(), and/or activate the matching tab?`

**Comment by grahamperrin** [comment]
A **Window** menu will alleviate/complement this; https://github.com/helloSystem/Menu/issues/21#issuecomment-753649543

**Comment by probonopd** [comment]
To reproduce:
* Put a folder on the desktop
* Double click the folder. Its window opens
* Double click the folder again. Another window opens. __Instead, the already-existing window should be brought to the front.__

**Comment by KDGNOR** [comment]
on macosx-finder it does not what write in bold text
just tested it :)

**Comment by probonopd** [comment]
See? helloSystem can do better than current macOS.

**Comment by kjarex** [comment]
I would see such a feature less favourable:

It for sure won’t be standard behaviour, but I have some folders which are usually just a horrible mess, like for example my “Download s” folder. Over time it ends up with literally thousands of items. Every now and then (when I finally agree that it became too messy), I clean it up. 

Usually I open the folder then (at least) twice. In one window I create new folders, let’s say for example a folder “ebooks” and in the other window I scroll then threw all the content, search for eBooks and once I found some, I go grab it, drag it into the other window and let it drop above/into the created “eBooks” folder (ebooks is just an example to give you somewhat an idea of my procedure, but might be not the best example to explain this way of cleaning up).

What I try to say is: I think there exist several use cases when a user would really like to have the same folder opened multiple times. And while I understand your intention, I don’t really see a huge advantage in bringing an already opened folder to the top instead of opening it again (or better: as nice it might seem, I don’t see a huge gain in such a behaviour - even if I’ve been not aware that I already had this folder open, an additional window won’t hurt he (if I’m already not aware of the first instance). Also let’s say I really wouldn’t have wanted the second window - I could just close it (not great, but no big deal either). With your feature on the other hand, I wouldn’t know how I could achieve to open it twice (which might be a bigger issue than just having to close something).

Maybe you haven’t considered such cases - or maybe you did, in which case it’s of course fine.

**Comment by probonopd** [comment]
No doubt @kjarex that there are use cases for what you are describing.
But as Steve Jobs famously said,

> You can't please all people all of the time. You only can please some people some of the time.

And in this case, we have firmly decided that each location in the filesystem can be opened in only one window.

(On Windows and may other systems I tend to involuntarily have the Downloads folder open in 10 different windows, and I hate it.)

**Comment by probonopd** [comment]
The intended behavior since has been implemented:

> Filer brings already-open windows to the front rather than opening multiple windows for the same folder, thanks __@moochris__

So closing here.

**Comment by kjarex** [comment]
Don’t get me wrong here - it’s not like I would be trying to keep the possibility to have a folder open multiple times for any cost - but I just stumbled over a different issue, and think it might be a perfect (and kinda consistent) solution - so I thought to share the idea (but it’s fine if you don’t like it) - here it comes:

Do it as you prefer, but if one opens an already opened folder while holding OPTION it opens the folder indeed another time. This would not only add an option for people who really want to open it another time intentionally, but would somewhat follow the idea of “OPTION while clicking on an Application to open instead the .app bundle” (as in “Yes I press OPTION to really open the folder, even though it’s not what usually a double click would do”). 

As I said, I’m fine with it, if you hate it and won’t implement it, but I just wanted to suggest it anyway (because I really like this particular idea).
