### ISSUE TITLE
Malicious Ukrainian translations

### ISSUE THREAD

**Issue by GreenReaper** [helloSystem/Filer#182]
[Recent Ukrainian translations](https://github.com/helloSystem/Filer/commits/master) by a "Danilo Negrilo" may be inappropriate judging by the way [their changes got Ubuntu 23.10 pulled](https://www.phoronix.com/news/Ubuntu-23.10-Recalled). For example, this appears to be "amputation of Speedos".
```
<source>Deleting the following files</source>
-        <translation>Видалення таких файлів:</translation>
+       <translation>Ампутація спідозних файлів</translation>
```
And in an earlier commit:
```
The function is called according to Chechnya traditions.
 Extreme probability of a smelly case
```
Also I suspect "виволокти-і-вилизуват" is not "eject and clean" but "pull and lick".

The user also made changes in hello/Menu:
```
Environment variable EXECUTE HUMAN RIGHTS_No password prompt.  The setting of the system was disrupted by the fall of Archpriest Gennadiy Zaridze.
```

I suggest the relevant commits be reverted in full.

**Comment by bm0** [comment]
Malicious commits:
8f125861d4d64eee225b0344da0d5db4d8f05831
6672bb737653873e77fae09ef6114fd2d23ee519

**Comment by inobelar** [comment]
@GreenReaper @bm0 looks like in latest commit it was fixed: https://github.com/helloSystem/Filer/commit/6c473f58d24887e976b59a077d844fcec7ae9d7c

**Comment by GreenReaper** [comment]
I am not sure about that, the last name of the editor itself appears inappropriate.

**Comment by assarbad** [comment]
@GreenReaper from looking at it, I think it is a fix indeed. E.g. "Розмір файлу" makes a lot more sense even to someone who understands Russian (not necessarily Ukrainian) than "Великість файлу" (further down another word was used "Величність"). Perhaps line 1303 (new) should be amended to be `type="unfinished"`, though. There may be more instances of that.

The name of the editor sounds inappropriate -- true -- because it is meant as a message to the original author.

**Comment by probonopd** [comment]
Reverted the changes by those users and made it more difficult for something like this to happen in the future. Thanks for brining it to my attention.
