### ISSUE TITLE
Set desktop background color and wallpaper earlier

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#84]
Currently when started with `--desktop`, Filer seems to do a lot of stuff including time-consuming `checkWhetherAppDirOrBundle` checks before it sets the desktop background, resulting in a ugly black desktop beckground for longer than needed.

Could we set the desktop background color and wallpaper first thing when Filer is started with `--desktop`, before doing anything else?

**Comment by moochris** [comment]
I checked this again and it now seems to have been fixed with https://github.com/helloSystem/Filer/pull/88

I guess applying the stylesheet to child widgets slowed things somehow. I tested by reverting that fix and we got the previous behaviour. After the fix for the stylesheet in https://github.com/helloSystem/Filer/pull/88, there is no long delay on showing the desktop with wallpaper.

**Comment by moochris** [comment]
Very strange, but the delay is still there when running from `/System/Filer`...

I get a long pause after `probono: FolderModel created`.

If I run directly from on the `$PATH` or within the build area of Filer, I don't get the delay. Is there some weirdness going on when the current working directory is inside an AppDir?

**Comment by linuxkettle** [comment]
This seems to be a chicken-and-egg problem: If you start Filer before Menu, it uses its own menu bar instead of the global one. If you start Menu before Filer, you get a grey openbox background while Filer is waiting for the Menu to start.

Another alternative is to start another executable that renders the desktop and exits after 3 seconds, or to make start-hello not switch the VT to the one with the X display until hello has actually started, the latter could be hard though.

**Comment by probonopd** [comment]
Yes, we might want to make a super tiny Qt executable that would do nothing but set the desktop wallpaper. This would be launched first thing after Xorg.

**Comment by probonopd** [comment]
https://github.com/helloSystem/Filer/commit/12ed8f81ee6b47659c7289cc153ed619c1e0e9bf adds the possibility to set the wallpaper to "Transparent". This enables the use of a 3rd party application outside of Filer to set the wallpaper even before Filer is being launched.

**Comment by linuxkettle** [comment]
Oh goody. Then I can use animated wallpapers!

**Comment by linuxkettle** [comment]
Also, there's a bit we could do to improve the KWin startup: the desktop goes black, the dock pops up, the menu shows, the screen goes black again, then tge dock and menu show back again, then we get a desktop background.

**Comment by probonopd** [comment]
> Also, there's a bit we could do to improve the KWin startup: the desktop goes black, the dock pops up, the menu shows, the screen goes black again, then tge dock and menu show back again, then we get a desktop background.

Exactly, ideally the real background would be loaded as soon as Xorg comes up, and stay there.
